export const mapElement = document.getElementById('map')! as HTMLDivElement;
export const form = document.querySelector('form')!;
export const locationInput = document.getElementById('location')! as HTMLInputElement;
export const elevation = document.getElementById('elevation')! as HTMLLIElement;
export const weatherDescription = document.getElementById('weather-description')! as HTMLLIElement;
export const temperature = document.getElementById('temperature')! as HTMLLIElement;
export const locationInformation = document.getElementById('location-info')! as HTMLDivElement;
export const stateDropdown = document.getElementById('state-select')! as HTMLSelectElement;
export const countyDropdown = document.getElementById('county-select')! as HTMLSelectElement;